### ISSUE TITLE
Not Making Access File - Valid Source File Isn't Found - HD Source File - 1440 x 1080

### ISSUE THREAD

**Issue by greglisidhc** [DanceHeritageCoalition/dpdpscripts#4]
Dances-Mac-Pro:~ DHCNYC$ makeaccess /Users/DHCNYC/Desktop/Susan_Marshall/DHCNY_030 
 2015-03-16T08:14:54 - A valid source file isn't found.

![screen shot 2015-03-16 at 8 19 48 am](https://cloud.githubusercontent.com/assets/9617776/6665912/728cce7a-cbb5-11e4-81b7-34c4b8928849.jpg)

Codec: MPEG-2
Wrapper: MOV
Format: HDV 1080i

**Comment by dericed** [comment]
Looks like the file has no extension. Do you mind add ".mov" to it.

**Comment by greglisidhc** [comment]
Adding the extension worked! So simple, don't know how I overlooked it. Thanks, Dave!
