### ISSUE TITLE
makeaccess cannot find source file information

### ISSUE THREAD

**Issue by savcampbell** [DanceHeritageCoalition/dpdpscripts#5]
makeaccess is running into critical errors, both on its own as well as when running packager. 

It appears as though the issue is with makeaccess not being able to look up information about the source file using mmfuncions scripts. It cannot locate the get_height, get_width, etc. commands in order to determine how to transcode the file. @dericed please advise

Here is the complete error message: 

MMDGs-MacBook-Air:~ archive$ makeaccess /Volumes/MMDG_001/Savannah\'s\ Test\ Files\ \(do\ not\ delete\)/B4_19XX_1005/objects/B4_19XX_1005_ffv1.mkv 
  [makeaccess] 2017-08-24T11:45:36 - Running: mkdir -p /Volumes/MMDG_001/Savannah's Test Files (do not delete)/B4_19XX_1005/objects/access
/usr/local/bin/makeaccess: line 67: get_height: command not found
/usr/local/bin/makeaccess: line 68: get_width: command not found
/usr/local/bin/makeaccess: line 69: get_dar: command not found
/usr/local/bin/makeaccess: line 70: get_videostreamcount: command not found
/usr/local/bin/makeaccess: line 71: get_audiostreamcount: command not found
/usr/local/bin/makeaccess: line 121: get_audio_mapping: command not found
  [makeaccess] 2017-08-24T11:45:36 - Running: ffmpeg -vsync 0 -nostdin -i  -f mp4 /Volumes/MMDG_001/Savannah's Test Files (do not delete)/B4_19XX_1005/objects/access/B4_19XX_1005_ffv1.mp4
ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.1.2_1/include/openjpeg-2.1 --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
: No such file or directory
  2017-08-24T11:45:36 -  [makeaccess]Error: Running: "ffmpeg -vsync 0 -nostdin -i  -f mp4 /Volumes/MMDG_001/Savannah's Test Files (do not delete)/B4_19XX_1005/objects/access/B4_19XX_1005_ffv1.mp4" gave an Error Code - 1
  2017-08-24T11:45:36 -  [makeaccess]The process ran into a critical error and can not proceed.

**Comment by dericed** [comment]
I looks like it depends on functions from https://github.com/mediamicroservices/mm/blob/master/mmfunctions but at one point in mmfunctions, the functions were all prefixed with an underscore but that change hasn't been applied here. You might be able to fix it by changing `get_height` to `_get_height`, etc for each mmfunction.

**Comment by savcampbell** [comment]
I am still getting the same error message after adding the underscore prefix to all of the mmfuncitons.

**Comment by savcampbell** [comment]
Fixed in #6
